<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>AndroidPhotoTransfer</AssemblyName>
    <RootNamespace>AndroidPhotoTransfer</RootNamespace>
    <Product>Android Photo Transfer</Product>
    <Version>1.0.1</Version>
    <TieredPGO>true</TieredPGO>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MediaDevices" Version="1.9.1" />
    <PackageReference Include="sqlite-net-pcl" Version="1.11.285" />
    <PackageReference Include="VirtualizingWrapPanel" Version="2.5.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AndroidPhotoTransfer.Tests" />
  </ItemGroup>

</Project>
